### PR TITLE
Update gems, remove bolierplate and bad binstubs

### PR DESCRIPTION
**Pull request by tatyree**
When I commissioned the repo, I accidentally installed all the binstubs
into a guard subdiretory and didn't notice. I've remvoed these now.

The bundle was updated as part of the installtion on my personal machine
- a slightly newer version of bundler.

The bolierplate should have been zapped when commissioning.

### CODE REVIEW

**Comment by SteveMarshall** [comment]
This looks good, but can you split this into one commit per change, please, so that it's clear to others which changes relate to which piece of work?

**Comment by tatyree** [comment]
While it is conceptually separate units of work, it could also be viewed collectively as 'housekeeping'.  Unless you have serious objections, I'd prefer to focus my efforts on something with greater utility.

**Comment by SteveMarshall** [comment]
Thanks for the update. Looking back at f2a8582d13bf424c7ac5153ddc64af3b934a4515, it looks like there's boilerplate left in a bunch of other files too. For example: `db/schema.rb`, `features/support/env.rb`, `spec/rails_helper.rb`. Basically, any comment that explains to us how to use the file that's there.

**Comment by tatyree** [comment]
Ok.  On it.

**Comment by tatyree** [comment]
Done.  I've deliberately left the boilerplate in the various test directories as removal would conflict with work that I'm about to push for the first payment screens (where there are actual tests).  I'll remove the boilerplate from those files as part of that PR.

**Pull request merged**
